# Generated by Django 3.2.12 on 2022-02-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_date', models.CharField(max_length=16)),
                ('deal_type', models.CharField(choices=[('real_rank', '실시간'), ('market_rank', '일간')], max_length=16)),
                ('market', models.CharField(choices=[('google', '구글플레이'), ('apple', '앱스토어'), ('one', '원스토어')], max_length=16)),
                ('rank_type', models.CharField(choices=[('free', '무료 순위'), ('paid', '유료 순위'), ('gross', '매출 순위')], max_length=16)),
                ('app_name', models.TextField(max_length=64)),
                ('icon_url', models.URLField()),
                ('market_appid', models.TextField(max_length=64)),
                ('package_name', models.TextField(max_length=64)),
                ('rank', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
